### ISSUE TITLE
Crash/Mod Compatibility Problem

### ISSUE THREAD

**Issue by ghost** [Zeno410/Geographicraft#1]
on main menu we have a problem. please read the log file
[fml-client-latest.txt](https://github.com/Zeno410/Geographicraft/files/720020/fml-client-latest.txt)
and please, look at here too: https://github.com/superbas11/MenuMobs/issues/21

**Comment by bschoenmaeckers** [comment]
This crash happens sometimes when the FMLServerstopped event got fired after the client got back to the main menu. Because of this, your dimensionManager isn't shotdown when I create my fakeworld to load the menu mobs in. I cant detect on my side when all the event handles got fired after the server stops. Do you have a solution for our problem?

**Comment by bschoenmaeckers** [comment]
This issue can be closed. Found a fix on my side.
